# Generated by Django 5.0.4 on 2024-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="must_complete_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
